
# Embeddings
embedding-provider: voyage
embedding-model: voyage-code-3
tokens-per-chunk: 800
chunks-per-batch: 64

# Vector store
vector-store-provider: chroma

# LLM
llm-provider: together
llm-model: Qwen/Qwen2.5-Coder-32B-Instruct

# Reranking
reranking-provider: voyage
reranking-model: rerank-2-lite